### ISSUE TITLE
Revisiting a tab in a running course/scenario fails to load

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#381]
**What happened**:
Using a service, I have created a tab in the lab using iframes. On initial load, the tab and the iframe contents load as expected. If you click away from the tab and click the tab again, it never loads and eventually throws "An Error Has Occurred" with the refresh button. Clicking on the refresh button does nothing.

**What you expected to happen**:
Clicking away from the tab and clicking back on the tab will resume whatever content was in the tab.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a VM template.
2. Add a service to the VM template. Set the following options: Has a Webinterface, Has it's own tab, port 81, path /, and under advanced proxy, only have `host header rewriting` checked.
3. Add VM template to environment.
4. Use environment in a scheduled event.
5. Launch the environment in the User interface.
6. Install Docker and run `docker run -itd --name nginx-81 -p 81:80 nginx`.
7. Click on the tab. The content should load with the generic `Welcome to nginx!` page.
8. Click away from the tab back to the shell.
9. Click on the tab. The error should now be shown.

**Anything else we need to know?**:
It looks like there is an access control error that is possibly causing the issue. The following is from the browser console. Notice the `Failed to load resource: Origin http://ui.192-168-`. It looks like its cutting off the full path?
```bash
! Origin http:/ui.192-168-4-62.sslip.io is not allowed by Access-Control-Allow-Origin. Status code: 200
4 XMLHttpRequest cannot load https://shell.192-168-4-62.sslip.io/pa/eyJhbGciOiJIUz/1NilsInR5cCI6|kpXVCJ9.eyJIbWEpbCI61mFkbWIuliwiZXhwljoxNjk3Nz/10TILCJuYmYiOjE20Tc2MzkIMjV9.wkqhC4HT_1DAd4WgKgLt2kr91EcobxitO_=eqtcl5uk/dynamic-nkjs5123dp=3178ef0b/81/ due to access
control checks.
! Failed to load resource: Origin http://ui.192-168-
https://shell.192-168-4-62.sslip.io/pa/eyJhbGciOiJIUz/1NilsInR5cCI6|kpXVCJ9.eyJIbWEpbC|6ImFkbWluliwiZXhwljoxNjk3Nz/10T/LCJuYmYiOjE20Tc2Mzk1MjV9.wkghC4HT_1DAd4WgKgLt2kr9|EcobxrtO_-eqtcluk/dynamic-nkjs5123dp-3178ef0b/81/
4-62.sslip.io is not allowed by Access-Control-Allow-Origin. Status code:
```

**Environment**:
- Gargantua version: hobbyfarm/gargantua:v3.0.1-rc0
- UI/Admin version: hobbyfarm/admin-ui:v3.0.0, hobbyfarm/ui:v3.0.0
- Kubernetes version (use `kubectl version`): K3s v1.27.6+k3s1
- Cloud provider or hardware configuration:
```bash
6-core CPU
64GB RAM
50GB Disk
```
- OS (e.g: `cat /etc/os-release`):
```bash
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by jggoebel** [comment]
duplicate of https://github.com/hobbyfarm/hobbyfarm/issues/355

**Comment by jggoebel** [comment]
the path seems not cut off- it is just 2 lines below. Seems like this is resolved if #355 is resolved.

**Comment by eengelking** [comment]
I'm not sure this is a duplicate of [#355](https://github.com/hobbyfarm/hobbyfarm/issues/355). While fixing the refresh problem may resolve the initial problem, there is still an `access control` error that has occurred.  If someone wants to refresh the framed window, this may still occur.

My team has use-cases where we will absolutely want the user to refresh the iframe window to see how changes are made to content over time. If the user refreshes and gets the `access control` error, this would be problematic.

**Comment by jggoebel** [comment]
What kind of application was deployed? I had code-server installed and reloading went through without any problem. The revisiting tab issue is fixed inside master.

**Comment by eengelking** [comment]
Sorry, I missed this comment.  I will re-test with the latest releases next week to see if I'm still having the same problem.

**Comment by jggoebel** [comment]
Had you time to test this again?

**Comment by eengelking** [comment]
> Had you time to test this again?

I have not. I created a new tool which allows us to bypass the need of web services. I hope to give you all a demo in a week or so.
